services:
  order-db:
    image: postgres:16
    container_name: order-db
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
    ports:
      - "15432:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data

volumes:
  order-db-data: