spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:15432/order_db
    username: ${DB_USERNAME:order_user}
    password: ${DB_PASSWORD:order_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8081

services:
  product:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8082}
    connect-timeout: 2s
    read-timeout: 5s