spring:
  application:
    name: product-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15433/product_db}
    username: ${DB_USERNAME:product_user}
    password: ${DB_PASSWORD:product_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: ${PORT:8082}
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,circuitbreakers
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] [%X{correlationId}] %-5level %logger{36} - %msg%n"